In [3]:
import pandas as pd

df = pd.read_csv('loan.csv')

print(f'Total rows: {df.shape[0]}')
print(f'Total columns: {df.shape[1]}')

/tmp/ipython-input-4268715030.py:3: DtypeWarning: Columns (19,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('loan.csv')

Total rows: 925454
Total columns: 145

In [4]:
# What are the loan statuses and how many are there in each category?
df['loan_status'].value_counts()

loan_status
Current               587494
Fully Paid            246458
Charged Off            73066
Late (31-120 days)     11441
In Grace Period         4894
Late (16-30 days)       2080
Default                   21
Name: count, dtype: int64

In [5]:
# What are the loan purpose categories and how many per category?
df['purpose'].value_counts()

purpose
debt_consolidation    506088
credit_card           218519
home_improvement       63618
other                  63198
major_purchase         21933
medical                11997
car                     9741
small_business          9323
house                   7412
vacation                6729
moving                  6315
renewable_energy         574
wedding                    7
Name: count, dtype: int64

In [6]:
# what are the mising values
print(df.isnull().sum())

id                       925454
member_id                925454
loan_amnt                     0
funded_amnt                   0
funded_amnt_inv               0
                          ...
settlement_status        914210
settlement_date          914210
settlement_amount        914210
settlement_percentage    914210
settlement_term          914210
Length: 145, dtype: int64

In [15]:
# display interest ranges within each loan grade
df.groupby('grade')['int_rate'].describe()

          count       mean       std   min    25%    50%    75%    max
grade
A      205602.0   7.015903  0.991892  5.31   6.11   7.21   7.84   8.81
B      274614.0  10.590266  1.100070  6.00   9.75  10.72  11.47  12.98
C      257527.0  14.249122  1.278505  6.00  13.49  14.07  15.04  16.91
D      127510.0  18.928347  1.627982  6.00  17.97  18.94  19.99  22.35
E       44570.0  23.590913  2.227990  6.00  21.97  23.88  25.34  27.27
F       12429.0  26.758497  2.478105  6.00  24.99  26.49  28.72  30.75
G        3202.0  29.252214  1.600864  6.00  28.18  28.99  30.79  30.99

# Simple Summary Table
Want to show grade, loan amount, if it was paid or charged off. Limited to matured loans, as we want to extract all the historical data we can.

Brief insights:
- Grade A loans (less interest rate) appear more likely to be fully paid off compared to grade G loans.
- Higher interest loans seem to have much worse charge off rates; need to calculate whether or not the higher interest compensates.

In [14]:
completed_loans = df[df['loan_status'].isin(['Fully Paid', 'Charged Off'])]

summary_table = completed_loans[['grade', 'loan_status']]
summary_table.groupby(['grade','loan_status']).size()

grade  loan_status
A      Charged Off     3931
       Fully Paid     50864
B      Charged Off    15229
       Fully Paid     79484
C      Charged Off    23995
       Fully Paid     69526
D      Charged Off    16144
       Fully Paid     30589
E      Charged Off     8714
       Fully Paid     11607
F      Charged Off     3869
       Fully Paid      3512
G      Charged Off     1184
       Fully Paid       876
dtype: int64